# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
from decimal import Decimal


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BinaryModel',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Tmax', models.DecimalField(verbose_name=b'Tmax', max_digits=12, decimal_places=4)),
                ('e_Tmax', models.DecimalField(verbose_name=b'sig(Tmax)', max_digits=12, decimal_places=4)),
                ('tau', models.DecimalField(verbose_name=b'T_E', max_digits=12, decimal_places=4)),
                ('e_tau', models.DecimalField(verbose_name=b'sig(T_E)', max_digits=12, decimal_places=4)),
                ('umin', models.DecimalField(verbose_name=b'u_min', max_digits=12, decimal_places=4)),
                ('e_umin', models.DecimalField(verbose_name=b'u_min', max_digits=12, decimal_places=4)),
                ('mass_ratio', models.DecimalField(verbose_name=b'q', max_digits=12, decimal_places=4)),
                ('e_mass_ratio', models.DecimalField(verbose_name=b'q', max_digits=12, decimal_places=4)),
                ('separation', models.DecimalField(verbose_name=b's', max_digits=12, decimal_places=4)),
                ('e_separation', models.DecimalField(verbose_name=b's', max_digits=12, decimal_places=4)),
                ('angle_a', models.DecimalField(verbose_name=b'alpha', max_digits=12, decimal_places=4)),
                ('e_angle_a', models.DecimalField(verbose_name=b'sig(alpha)', max_digits=12, decimal_places=4)),
                ('rho', models.DecimalField(null=True, verbose_name=b'rho', max_digits=12, decimal_places=4, blank=True)),
                ('e_rho', models.DecimalField(null=True, verbose_name=b'sig(rho)', max_digits=12, decimal_places=4, blank=True)),
                ('pi_e_n', models.DecimalField(null=True, verbose_name=b'Parallax EN', max_digits=12, decimal_places=4, blank=True)),
                ('e_pi_e_n', models.DecimalField(null=True, verbose_name=b'sig(Parallax EN)', max_digits=12, decimal_places=4, blank=True)),
                ('pi_e_e', models.DecimalField(null=True, verbose_name=b'Parallax EE', max_digits=12, decimal_places=4, blank=True)),
                ('e_pi_e_e', models.DecimalField(null=True, verbose_name=b'sig(Parallax EE)', max_digits=12, decimal_places=4, blank=True)),
                ('dsdt', models.DecimalField(null=True, verbose_name=b'Orbital motion ds/dt', max_digits=12, decimal_places=4, blank=True)),
                ('e_dsdt', models.DecimalField(null=True, verbose_name=b'sig(Orbital motion ds/dt)', max_digits=12, decimal_places=4, blank=True)),
                ('dadt', models.DecimalField(null=True, verbose_name=b'Orbital motion da/dt', max_digits=12, decimal_places=4, blank=True)),
                ('e_dadt', models.DecimalField(null=True, verbose_name=b'sig(Orbital motion da/dt)', max_digits=12, decimal_places=4, blank=True)),
                ('modeler', models.CharField(default=b'', max_length=25, verbose_name=b'Modeler', blank=True)),
                ('last_updated', models.DateTimeField(verbose_name=b'date last updated')),
            ],
        ),
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('datafile', models.CharField(max_length=1000)),
                ('last_upd', models.DateTimeField(verbose_name=b'date last updated')),
                ('last_obs', models.DateTimeField(verbose_name=b'date of last observation')),
                ('last_mag', models.DecimalField(max_digits=10, decimal_places=2)),
                ('tel', models.CharField(default=b'', max_length=50, blank=True)),
                ('inst', models.CharField(default=b'', max_length=50, blank=True)),
                ('filt', models.CharField(default=b'', max_length=50, blank=True)),
                ('baseline', models.DecimalField(default=22.0, max_digits=6, decimal_places=2, blank=True)),
                ('g', models.DecimalField(default=0.0, max_digits=6, decimal_places=2, blank=True)),
                ('ndata', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('ev_ra', models.CharField(max_length=50, verbose_name=b'RA')),
                ('ev_dec', models.CharField(max_length=50, verbose_name=b'Dec')),
                ('bright_neighbour', models.BooleanField(default=False, verbose_name=b'Bright neighbour')),
                ('status', models.CharField(default=b'EX', max_length=12, verbose_name=b'Event status', choices=[(b'CH', b'check'), (b'AC', b'active'), (b'AN', b'anomaly'), (b'RE', b'rejected'), (b'EX', b'expired')])),
            ],
        ),
        migrations.CreateModel(
            name='EventName',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=50, verbose_name=b'Survey Event Name')),
                ('event', models.ForeignKey(related_name='event_id', to='events.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=50, verbose_name=b'Filter name', blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('image_name', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(verbose_name=b'Date received')),
                ('date_obs', models.DateTimeField(verbose_name=b'Date of observation')),
                ('tel', models.CharField(default=b'', max_length=50, blank=True)),
                ('inst', models.CharField(default=b'', max_length=50, blank=True)),
                ('filt', models.CharField(default=b'', max_length=50, blank=True)),
                ('grp_id', models.CharField(default=b'', max_length=30, blank=True)),
                ('track_id', models.CharField(default=b'', max_length=30, blank=True)),
                ('req_id', models.CharField(default=b'', max_length=30, blank=True)),
                ('airmass', models.DecimalField(null=True, max_digits=10, decimal_places=2, blank=True)),
                ('avg_fwhm', models.DecimalField(null=True, max_digits=10, decimal_places=2, blank=True)),
                ('avg_sky', models.DecimalField(null=True, max_digits=10, decimal_places=2, blank=True)),
                ('avg_sigsky', models.DecimalField(null=True, max_digits=10, decimal_places=2, blank=True)),
                ('moon_sep', models.DecimalField(null=True, max_digits=10, decimal_places=2, blank=True)),
                ('moon_phase', models.DecimalField(null=True, max_digits=10, decimal_places=2, blank=True)),
                ('moon_up', models.BooleanField(default=False)),
                ('elongation', models.DecimalField(null=True, max_digits=10, decimal_places=2, blank=True)),
                ('nstars', models.IntegerField(null=True, blank=True)),
                ('ztemp', models.DecimalField(null=True, max_digits=10, decimal_places=2, blank=True)),
                ('quality', models.CharField(default=b'', max_length=400, blank=True)),
                ('target_hjd', models.DecimalField(null=True, max_digits=20, decimal_places=5, blank=True)),
                ('target_mag', models.DecimalField(null=True, max_digits=15, decimal_places=5, blank=True)),
                ('target_magerr', models.DecimalField(null=True, max_digits=15, decimal_places=5, blank=True)),
                ('target_skybg', models.DecimalField(null=True, max_digits=15, decimal_places=5, blank=True)),
                ('target_fwhm', models.DecimalField(null=True, max_digits=10, decimal_places=3, blank=True)),
                ('event', models.ForeignKey(to='events.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=50, verbose_name=b'Instrument name')),
                ('pixscale', models.DecimalField(null=True, verbose_name=b'Pixel scale (arcsec/pix)', max_digits=12, decimal_places=4, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(default=b'Other', max_length=50, verbose_name=b'Operator Name')),
            ],
        ),
        migrations.CreateModel(
            name='RobonetReduction',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('lc_file', models.CharField(max_length=1000)),
                ('timestamp', models.DateTimeField(verbose_name=b'date created')),
                ('ref_image', models.CharField(max_length=1000)),
                ('target_found', models.BooleanField(default=False)),
                ('ron', models.DecimalField(default=Decimal('0.0'), max_digits=10, decimal_places=2)),
                ('gain', models.DecimalField(default=Decimal('1.0'), max_digits=10, decimal_places=2)),
                ('oscanx1', models.IntegerField(default=1)),
                ('oscanx2', models.IntegerField(default=50)),
                ('oscany1', models.IntegerField(default=1)),
                ('oscany2', models.IntegerField(default=500)),
                ('imagex1', models.IntegerField(default=51)),
                ('imagex2', models.IntegerField(default=1000)),
                ('imagey1', models.IntegerField(default=1)),
                ('imagey2', models.IntegerField(default=1000)),
                ('minval', models.DecimalField(default=Decimal('1.0'), max_digits=6, decimal_places=2)),
                ('maxval', models.DecimalField(default=Decimal('55000.0'), max_digits=10, decimal_places=2)),
                ('growsatx', models.IntegerField(default=0)),
                ('growsaty', models.IntegerField(default=0)),
                ('coeff2', models.DecimalField(default=Decimal('0.0000010'), max_digits=6, decimal_places=2)),
                ('coeff3', models.DecimalField(default=Decimal('1.0E-12'), max_digits=6, decimal_places=2)),
                ('sigclip', models.DecimalField(default=Decimal('4.5'), max_digits=6, decimal_places=2)),
                ('sigfrac', models.DecimalField(default=Decimal('0.5'), max_digits=6, decimal_places=2)),
                ('flim', models.DecimalField(default=Decimal('2.0'), max_digits=6, decimal_places=2)),
                ('niter', models.IntegerField(default=4)),
                ('use_reflist', models.IntegerField(default=0)),
                ('max_nimages', models.IntegerField(default=1)),
                ('max_sky', models.DecimalField(default=Decimal('5000.0'), max_digits=6, decimal_places=2)),
                ('min_ell', models.DecimalField(default=Decimal('0.8'), max_digits=6, decimal_places=2)),
                ('trans_type', models.CharField(default=b'P', max_length=100, choices=[(b'S', b'shift'), (b'R', b'rot_shift'), (b'M', b'rot_mag_shift'), (b'L', b'linear'), (b'P', b'polynomial')])),
                ('trans_auto', models.IntegerField(default=0)),
                ('replace_cr', models.IntegerField(default=0)),
                ('min_scale', models.DecimalField(default=Decimal('0.99'), max_digits=6, decimal_places=2)),
                ('max_scale', models.DecimalField(default=Decimal('1.01'), max_digits=6, decimal_places=2)),
                ('fov', models.DecimalField(default=Decimal('0.1'), max_digits=6, decimal_places=2)),
                ('star_space', models.IntegerField(default=30)),
                ('init_mthresh', models.DecimalField(default=Decimal('1.0'), max_digits=6, decimal_places=2)),
                ('smooth_pro', models.IntegerField(default=2)),
                ('smooth_fwhm', models.DecimalField(default=Decimal('3.0'), max_digits=6, decimal_places=2)),
                ('var_deg', models.IntegerField(default=1)),
                ('det_thresh', models.DecimalField(default=Decimal('2.0'), max_digits=6, decimal_places=2)),
                ('psf_thresh', models.DecimalField(default=Decimal('8.0'), max_digits=6, decimal_places=2)),
                ('psf_size', models.DecimalField(default=Decimal('8.0'), max_digits=6, decimal_places=2)),
                ('psf_comp_dist', models.DecimalField(default=Decimal('0.7'), max_digits=6, decimal_places=2)),
                ('psf_comp_flux', models.DecimalField(default=Decimal('0.1'), max_digits=6, decimal_places=2)),
                ('psf_corr_thresh', models.DecimalField(default=Decimal('0.9'), max_digits=6, decimal_places=2)),
                ('ker_rad', models.DecimalField(default=Decimal('2.0'), max_digits=6, decimal_places=2)),
                ('lres_ker_rad', models.DecimalField(default=Decimal('2.0'), max_digits=6, decimal_places=2)),
                ('subframes_x', models.IntegerField(default=1)),
                ('subframes_y', models.IntegerField(default=1)),
                ('grow', models.DecimalField(default=Decimal('0.0'), max_digits=6, decimal_places=2)),
                ('ps_var', models.IntegerField(default=0)),
                ('back_var', models.IntegerField(default=1)),
                ('diffpro', models.IntegerField(default=0)),
                ('event', models.ForeignKey(to='events.Event')),
            ],
        ),
        migrations.CreateModel(
            name='RobonetRequest',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('timestamp', models.DateTimeField(verbose_name=b'date last updated', blank=True)),
                ('pfrm_on', models.BooleanField(default=False)),
                ('onem_on', models.BooleanField(default=False)),
                ('twom_on', models.BooleanField(default=False)),
                ('t_sample', models.DecimalField(max_digits=6, decimal_places=2)),
                ('exptime', models.IntegerField()),
                ('request_type', models.CharField(default=b'M', max_length=20, choices=[(b'T', b'ToO'), (b'M', b'Monitor'), (b'S', b'Single')])),
                ('which_filter', models.CharField(default=b'', max_length=20, blank=True)),
                ('which_inst', models.CharField(default=b'', max_length=20, blank=True)),
                ('time_expire', models.DateTimeField(verbose_name=b'request expiry date', blank=True)),
                ('grp_id', models.CharField(default=b'', max_length=30, blank=True)),
                ('track_id', models.CharField(default=b'', max_length=30, blank=True)),
                ('req_id', models.CharField(default=b'', max_length=30, blank=True)),
                ('n_exp', models.IntegerField(default=1)),
                ('event', models.ForeignKey(to='events.Event')),
            ],
        ),
        migrations.CreateModel(
            name='RobonetStatus',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('timestamp', models.DateTimeField(verbose_name=b'date last updated')),
                ('status', models.CharField(default=b'AC', max_length=12, choices=[(b'CH', b'check'), (b'AC', b'active'), (b'AN', b'anomaly'), (b'EI', b'eoi'), (b'BA', b'baseline'), (b'EX', b'expired')])),
                ('comment', models.CharField(default=b'--', max_length=200)),
                ('updated_by', models.CharField(default=b'--', max_length=25)),
                ('rec_cad', models.DecimalField(null=True, verbose_name=b'Recommended cadence (hr)', max_digits=6, decimal_places=2, blank=True)),
                ('rec_texp', models.IntegerField(null=True, verbose_name=b'Recommended t_exp (sec)', blank=True)),
                ('rec_nexp', models.IntegerField(null=True, verbose_name=b'Recommended n_exp', blank=True)),
                ('rec_telclass', models.CharField(default=b'', max_length=12, verbose_name=b'Recommended telescope class', blank=True)),
                ('event', models.ForeignKey(to='events.Event')),
            ],
        ),
        migrations.CreateModel(
            name='SingleModel',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Tmax', models.DecimalField(verbose_name=b'Tmax', max_digits=12, decimal_places=4)),
                ('e_Tmax', models.DecimalField(verbose_name=b'sig(Tmax)', max_digits=12, decimal_places=4)),
                ('tau', models.DecimalField(verbose_name=b'T_E', max_digits=12, decimal_places=4)),
                ('e_tau', models.DecimalField(verbose_name=b'sig(T_E)', max_digits=12, decimal_places=4)),
                ('umin', models.DecimalField(verbose_name=b'u_min', max_digits=12, decimal_places=4)),
                ('e_umin', models.DecimalField(verbose_name=b'sig(u_min)', max_digits=12, decimal_places=4)),
                ('rho', models.DecimalField(null=True, verbose_name=b'rho', max_digits=12, decimal_places=4, blank=True)),
                ('e_rho', models.DecimalField(null=True, verbose_name=b'sig(rho)', max_digits=12, decimal_places=4, blank=True)),
                ('pi_e_n', models.DecimalField(null=True, verbose_name=b'Parallax EN', max_digits=12, decimal_places=4, blank=True)),
                ('e_pi_e_n', models.DecimalField(null=True, verbose_name=b'sig(Parallax EN)', max_digits=12, decimal_places=4, blank=True)),
                ('pi_e_e', models.DecimalField(null=True, verbose_name=b'Parallax EE', max_digits=12, decimal_places=4, blank=True)),
                ('e_pi_e_e', models.DecimalField(null=True, verbose_name=b'sig(Parallax EE)', max_digits=12, decimal_places=4, blank=True)),
                ('modeler', models.CharField(default=b'', max_length=25, verbose_name=b'Modeler', blank=True)),
                ('last_updated', models.DateTimeField(verbose_name=b'date last updated')),
                ('event', models.ForeignKey(to='events.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Tap',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('timestamp', models.DateTimeField(verbose_name=b'Date generated')),
                ('priority', models.CharField(default=b'L', max_length=12, choices=[(b'A', b'anomaly'), (b'H', b'high'), (b'M', b'medium'), (b'L', b'low')])),
                ('tsamp', models.DecimalField(default=0, max_digits=6, decimal_places=2, blank=True)),
                ('texp', models.IntegerField(default=0, blank=True)),
                ('nexp', models.IntegerField(default=0, blank=True)),
                ('telclass', models.CharField(default=b'', max_length=12, blank=True)),
                ('imag', models.DecimalField(default=22.0, max_digits=6, decimal_places=2, blank=True)),
                ('omega', models.DecimalField(null=True, max_digits=6, decimal_places=2, blank=True)),
                ('err_omega', models.DecimalField(null=True, max_digits=6, decimal_places=2, blank=True)),
                ('peak_omega', models.DecimalField(null=True, max_digits=6, decimal_places=2, blank=True)),
                ('blended', models.BooleanField(default=False)),
                ('event', models.ForeignKey(to='events.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Telescope',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=100, verbose_name=b'Telescope name')),
                ('aperture', models.DecimalField(null=True, verbose_name=b'Telescope Aperture (m)', max_digits=6, decimal_places=2, blank=True)),
                ('latitude', models.DecimalField(null=True, verbose_name=b'Latitude (N) in decimal degrees', max_digits=8, decimal_places=4, blank=True)),
                ('longitude', models.DecimalField(null=True, verbose_name=b'Longitude (E) in decimal degrees', max_digits=8, decimal_places=4, blank=True)),
                ('altitude', models.DecimalField(null=True, verbose_name=b'Altitude (m)', max_digits=8, decimal_places=4, blank=True)),
                ('site', models.CharField(default=b'', max_length=100, verbose_name=b'Site name', blank=True)),
                ('operator', models.ForeignKey(to='events.Operator')),
            ],
        ),
        migrations.AddField(
            model_name='instrument',
            name='telescope',
            field=models.ForeignKey(to='events.Telescope'),
        ),
        migrations.AddField(
            model_name='filter',
            name='instrument',
            field=models.ForeignKey(to='events.Instrument'),
        ),
        migrations.AddField(
            model_name='eventname',
            name='operator',
            field=models.ForeignKey(related_name='operator_id', to='events.Operator'),
        ),
        migrations.AddField(
            model_name='datafile',
            name='event',
            field=models.ForeignKey(to='events.Event'),
        ),
        migrations.AddField(
            model_name='binarymodel',
            name='event',
            field=models.ForeignKey(to='events.Event'),
        ),
    ]
