# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
from decimal import Decimal


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Binary_Model',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Tmax', models.DecimalField(verbose_name=b'Tmax', max_digits=12, decimal_places=4)),
                ('e_Tmax', models.DecimalField(verbose_name=b'sig(Tmax)', max_digits=12, decimal_places=4)),
                ('tau', models.DecimalField(verbose_name=b'T_E', max_digits=12, decimal_places=4)),
                ('e_tau', models.DecimalField(verbose_name=b'sig(T_E)', max_digits=12, decimal_places=4)),
                ('umin', models.DecimalField(verbose_name=b'u_min', max_digits=12, decimal_places=4)),
                ('e_umin', models.DecimalField(verbose_name=b'u_min', max_digits=12, decimal_places=4)),
                ('mass_ratio', models.DecimalField(verbose_name=b'q', max_digits=12, decimal_places=4)),
                ('e_mass_ratio', models.DecimalField(verbose_name=b'q', max_digits=12, decimal_places=4)),
                ('separation', models.DecimalField(verbose_name=b's', max_digits=12, decimal_places=4)),
                ('e_separation', models.DecimalField(verbose_name=b's', max_digits=12, decimal_places=4)),
                ('rho_finite', models.DecimalField(verbose_name=b'rho', max_digits=12, decimal_places=4)),
                ('angle_a', models.DecimalField(verbose_name=b'alpha', max_digits=12, decimal_places=4)),
                ('last_updated', models.DateTimeField(verbose_name=b'date last updated')),
            ],
        ),
        migrations.CreateModel(
            name='Data_File',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('datafile', models.CharField(max_length=1000)),
                ('last_updated', models.DateTimeField(verbose_name=b'date last updated')),
                ('last_magnitude', models.DecimalField(max_digits=10, decimal_places=2)),
                ('telescope', models.CharField(max_length=50)),
                ('version', models.IntegerField()),
                ('ndata', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('ev_name_ogle', models.CharField(default=b'...', max_length=200, verbose_name=b'OGLE id')),
                ('ev_name_moa', models.CharField(default=b'...', max_length=200, verbose_name=b'MOA id')),
                ('ev_name_kmt', models.CharField(default=b'...', max_length=200, verbose_name=b'KMT id')),
                ('ev_ra', models.CharField(max_length=50, verbose_name=b'RA')),
                ('ev_dec', models.CharField(max_length=50, verbose_name=b'Dec')),
                ('bright_neighbour', models.BooleanField(default=False, verbose_name=b'Bright neighbour')),
            ],
        ),
        migrations.CreateModel(
            name='Kmt_Detail',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Tmax', models.DecimalField(verbose_name=b'Tmax', max_digits=12, decimal_places=4)),
                ('tau', models.DecimalField(verbose_name=b'T_E', max_digits=12, decimal_places=4)),
                ('umin', models.DecimalField(verbose_name=b'u_min', max_digits=12, decimal_places=4)),
                ('last_updated', models.DateTimeField(verbose_name=b'date last updated')),
                ('url_link', models.URLField(max_length=400, verbose_name=b'KMT event url')),
                ('event', models.ForeignKey(to='events.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Moa_Detail',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Tmax', models.DecimalField(verbose_name=b'Tmax', max_digits=12, decimal_places=4)),
                ('tau', models.DecimalField(verbose_name=b'T_E', max_digits=12, decimal_places=4)),
                ('umin', models.DecimalField(verbose_name=b'u_min', max_digits=12, decimal_places=4)),
                ('last_updated', models.DateTimeField(verbose_name=b'date last updated')),
                ('url_link', models.URLField(max_length=400, verbose_name=b'MOA event url')),
                ('event', models.ForeignKey(to='events.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Ogle_Detail',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Tmax', models.DecimalField(verbose_name=b'Tmax', max_digits=12, decimal_places=4)),
                ('tau', models.DecimalField(verbose_name=b'T_E', max_digits=12, decimal_places=4)),
                ('umin', models.DecimalField(verbose_name=b'u_min', max_digits=12, decimal_places=4)),
                ('last_updated', models.DateTimeField(verbose_name=b'date last updated')),
                ('url_link', models.URLField(max_length=400, verbose_name=b'OGLE event url')),
                ('event', models.ForeignKey(to='events.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Robonet_Log',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('image_name', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(verbose_name=b'date created')),
                ('exptime', models.DecimalField(max_digits=10, decimal_places=2)),
                ('filter1', models.CharField(max_length=12)),
                ('filter2', models.CharField(max_length=12)),
                ('filter3', models.CharField(max_length=12)),
                ('telescope', models.CharField(max_length=50)),
                ('instrument', models.CharField(max_length=50)),
                ('group_id', models.CharField(max_length=80)),
                ('track_id', models.CharField(max_length=80)),
                ('req_id', models.CharField(max_length=80)),
                ('airmass', models.DecimalField(max_digits=10, decimal_places=2)),
                ('fwhm', models.DecimalField(max_digits=10, decimal_places=2)),
                ('sky_bg', models.DecimalField(max_digits=10, decimal_places=2)),
                ('sd_bg', models.DecimalField(max_digits=10, decimal_places=2)),
                ('moon_sep', models.DecimalField(max_digits=10, decimal_places=2)),
                ('elongation', models.DecimalField(max_digits=10, decimal_places=2)),
                ('nstars', models.IntegerField()),
                ('quality', models.CharField(max_length=400)),
                ('event', models.ForeignKey(to='events.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Robonet_Reduction',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('lc_file', models.CharField(max_length=1000)),
                ('timestamp', models.DateTimeField(verbose_name=b'date created')),
                ('version', models.IntegerField()),
                ('ref_image', models.CharField(max_length=1000)),
                ('ron', models.DecimalField(default=Decimal('0.0'), max_digits=10, decimal_places=2)),
                ('gain', models.DecimalField(default=Decimal('1.0'), max_digits=10, decimal_places=2)),
                ('oscanx1', models.IntegerField(default=1)),
                ('oscanx2', models.IntegerField(default=50)),
                ('oscany1', models.IntegerField(default=1)),
                ('oscany2', models.IntegerField(default=500)),
                ('imagex1', models.IntegerField(default=51)),
                ('imagex2', models.IntegerField(default=1000)),
                ('imagey1', models.IntegerField(default=1)),
                ('imagey2', models.IntegerField(default=1000)),
                ('minval', models.DecimalField(default=Decimal('1.0'), max_digits=6, decimal_places=2)),
                ('maxval', models.DecimalField(default=Decimal('55000.0'), max_digits=10, decimal_places=2)),
                ('growsatx', models.IntegerField(default=0)),
                ('growsaty', models.IntegerField(default=0)),
                ('coeff2', models.DecimalField(default=Decimal('0.0000010'), max_digits=6, decimal_places=2)),
                ('coeff3', models.DecimalField(default=Decimal('1.0E-12'), max_digits=6, decimal_places=2)),
                ('sigclip', models.DecimalField(default=Decimal('4.5'), max_digits=6, decimal_places=2)),
                ('sigfrac', models.DecimalField(default=Decimal('0.5'), max_digits=6, decimal_places=2)),
                ('flim', models.DecimalField(default=Decimal('2.0'), max_digits=6, decimal_places=2)),
                ('niter', models.IntegerField(default=4)),
                ('use_reflist', models.IntegerField(default=0)),
                ('max_nimages', models.IntegerField(default=1)),
                ('max_sky', models.DecimalField(default=Decimal('5000.0'), max_digits=6, decimal_places=2)),
                ('min_ell', models.DecimalField(default=Decimal('0.8'), max_digits=6, decimal_places=2)),
                ('trans_type', models.CharField(default=b'P', max_length=100, choices=[(b'S', b'shift'), (b'R', b'rot_shift'), (b'M', b'rot_mag_shift'), (b'L', b'linear'), (b'P', b'polynomial')])),
                ('trans_auto', models.IntegerField(default=0)),
                ('replace_cr', models.IntegerField(default=0)),
                ('min_scale', models.DecimalField(default=Decimal('0.99'), max_digits=6, decimal_places=2)),
                ('max_scale', models.DecimalField(default=Decimal('1.01'), max_digits=6, decimal_places=2)),
                ('fov', models.DecimalField(default=Decimal('0.1'), max_digits=6, decimal_places=2)),
                ('star_space', models.IntegerField(default=30)),
                ('init_mthresh', models.DecimalField(default=Decimal('1.0'), max_digits=6, decimal_places=2)),
                ('smooth_pro', models.IntegerField(default=2)),
                ('smooth_fwhm', models.DecimalField(default=Decimal('3.0'), max_digits=6, decimal_places=2)),
                ('var_deg', models.IntegerField(default=1)),
                ('det_thresh', models.DecimalField(default=Decimal('2.0'), max_digits=6, decimal_places=2)),
                ('psf_thresh', models.DecimalField(default=Decimal('8.0'), max_digits=6, decimal_places=2)),
                ('psf_size', models.DecimalField(default=Decimal('8.0'), max_digits=6, decimal_places=2)),
                ('psf_comp_dist', models.DecimalField(default=Decimal('0.7'), max_digits=6, decimal_places=2)),
                ('psf_comp_flux', models.DecimalField(default=Decimal('0.1'), max_digits=6, decimal_places=2)),
                ('psf_corr_thresh', models.DecimalField(default=Decimal('0.9'), max_digits=6, decimal_places=2)),
                ('ker_rad', models.DecimalField(default=Decimal('2.0'), max_digits=6, decimal_places=2)),
                ('lres_ker_rad', models.DecimalField(default=Decimal('2.0'), max_digits=6, decimal_places=2)),
                ('subframes_x', models.IntegerField(default=1)),
                ('subframes_y', models.IntegerField(default=1)),
                ('grow', models.DecimalField(default=Decimal('0.0'), max_digits=6, decimal_places=2)),
                ('ps_var', models.IntegerField(default=0)),
                ('back_var', models.IntegerField(default=1)),
                ('diffpro', models.IntegerField(default=0)),
                ('event', models.ForeignKey(to='events.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Robonet_Request',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('timestamp', models.DateTimeField(verbose_name=b'date last updated')),
                ('onem_on', models.BooleanField(default=False)),
                ('twom_on', models.BooleanField(default=False)),
                ('t_sample', models.DecimalField(max_digits=6, decimal_places=2)),
                ('exptime', models.IntegerField()),
                ('which_filter', models.CharField(default=b'ip', max_length=12)),
                ('event', models.ForeignKey(to='events.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Robonet_Status',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('timestamp', models.DateTimeField(verbose_name=b'date last updated')),
                ('priority', models.CharField(default=b'L', max_length=12, choices=[(b'A', b'anomaly'), (b'H', b'high'), (b'M', b'medium'), (b'L', b'low')])),
                ('status', models.CharField(default=b'AC', max_length=12, choices=[(b'CH', b'check'), (b'AC', b'active'), (b'AN', b'anomaly'), (b'RE', b'rejected'), (b'EX', b'expired')])),
                ('comment', models.CharField(default=b'--', max_length=200)),
                ('updated_by', models.CharField(default=b'--', max_length=25)),
                ('event', models.ForeignKey(to='events.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Single_Model',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Tmax', models.DecimalField(verbose_name=b'Tmax', max_digits=12, decimal_places=4)),
                ('e_Tmax', models.DecimalField(verbose_name=b'sig(Tmax)', max_digits=12, decimal_places=4)),
                ('tau', models.DecimalField(verbose_name=b'T_E', max_digits=12, decimal_places=4)),
                ('e_tau', models.DecimalField(verbose_name=b'sig(T_E)', max_digits=12, decimal_places=4)),
                ('umin', models.DecimalField(verbose_name=b'u_min', max_digits=12, decimal_places=4)),
                ('e_umin', models.DecimalField(verbose_name=b'u_min', max_digits=12, decimal_places=4)),
                ('last_updated', models.DateTimeField(verbose_name=b'date last updated')),
                ('event', models.ForeignKey(to='events.Event')),
            ],
        ),
        migrations.AddField(
            model_name='data_file',
            name='event',
            field=models.ForeignKey(to='events.Event'),
        ),
        migrations.AddField(
            model_name='binary_model',
            name='event',
            field=models.ForeignKey(to='events.Event'),
        ),
    ]
