# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tap',
            name='cadence',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='tap',
            name='cost1m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='tap',
            name='visibility',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[(b'CH', b'check'), (b'AC', b'active'), (b'AN', b'anomaly'), (b'EI', b'eoi'), (b'BA', b'baseline'), (b'EX', b'expired')], default=b'EX', max_length=12, verbose_name=b'Event status'),
        ),
    ]
