# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-23 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubObsRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_id', models.CharField(blank=True, max_length=30)),
                ('grp_id', models.CharField(blank=True, max_length=30)),
                ('track_id', models.CharField(blank=True, max_length=30)),
                ('window_start', models.DateTimeField(blank=True, verbose_name=b'subrequest start time')),
                ('window_end', models.DateTimeField(blank=True, verbose_name=b'subrequest end time')),
                ('status', models.CharField(choices=[(b'PENDING', b'PENDING'), (b'COMPLETED', b'COMPLETED'), (b'CANCELED', b'CANCELED'), (b'WINDOW_EXPIRED', b'WINDOW_EXPIRED')], default=b'PENDING', max_length=40)),
                ('time_executed', models.DateTimeField(blank=True, null=True, verbose_name=b'subrequest executed time')),
            ],
        ),
    ]
