# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tap',
            name='ipp',
            field=models.DecimalField(blank=True, decimal_places=3, default=1.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='obsrequest',
            name='timestamp',
            field=models.DateTimeField(blank=True, verbose_name=b'request submit date'),
        ),
    ]
