# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-20 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_subobsrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='subobsrequest',
            name='grp_id',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='subobsrequest',
            name='track_id',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
