# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20170327_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tap',
            name='priority',
            field=models.CharField(choices=[(b'A', b'REA High'), (b'L', b'REA Low'), (b'B', b'REA Post-High'), (b'N', b'None')], default=b'N', max_length=12),
        ),
    ]
