# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-26 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20170125_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='rome_field',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
