# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-20 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20180420_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subobsrequest',
            name='time_executed',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'subrequest executed time'),
        ),
    ]
