# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-24 07:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datafile',
            name='event',
        ),
        migrations.DeleteModel(
            name='DataFile',
        ),
    ]
