# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-04 05:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20170504_0400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='shiftx',
            new_name='shift_x',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='shifty',
            new_name='shift_y',
        ),
    ]
