# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-29 16:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_datafile'),
        ('events', '0004_auto_20170504_0537'),
    ]

    operations = [
    ]
