# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-20 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20180420_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='subobsrequest',
            name='sr_id',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
