# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-23 21:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_datafile'),
        ('events', '0005_subobsrequest_sr_id'),
    ]

    operations = [
    ]
